#!/bin/bash
# File: scripts/detect_unguarded_calls.sh
# Description: Detect unguarded external command calls in Bash libraries
# Usage: ./detect_unguarded_calls.sh <library_file>
# Author: Generated by software-configuration-management skill

set -euo pipefail

# Check arguments
if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <library_file>" >&2
    echo "Detect unguarded external command calls in a Bash library" >&2
    echo "The script unsets PATH and sources the library to catch unguarded calls" >&2
    exit 1
fi

LIBRARY_FILE="$1"

if [[ ! -f "$LIBRARY_FILE" ]]; then
    echo "ERROR: Library file '$LIBRARY_FILE' not found" >&2
    exit 1
fi

if [[ ! -r "$LIBRARY_FILE" ]]; then
    echo "ERROR: Library file '$LIBRARY_FILE' is not readable" >&2
    exit 1
fi

echo "Analyzing library: $LIBRARY_FILE"
echo "Unsetting PATH to detect unguarded external command calls..."
echo

# Source the command guard library BEFORE unsetting PATH
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(dirname "$SCRIPT_DIR")"
CONFIG_DIR="$(dirname "$SKILL_DIR")/../../config"

if [[ ! -f "$CONFIG_DIR/command_guard.sh" ]]; then
    echo "ERROR: command_guard.sh not found at $CONFIG_DIR/command_guard.sh" >&2
    exit 1
fi

source "$CONFIG_DIR/command_guard.sh"

# Guard the commands we need for analysis
guard grep awk

# Unset PATH to force failure of unguarded external commands
# Only built-in commands and functions will work
unset PATH

# Track if any unguarded calls were detected
UNGUARDED_CALLS_DETECTED=false

# Source the library in a subshell to isolate the analysis
# Capture both stdout and stderr
OUTPUT=$( (
    echo "Sourcing library in restricted environment..."
    source "$LIBRARY_FILE" 2>&1 || true
    echo "Library sourced successfully"
) 2>&1 )
if echo "$OUTPUT" | grep -q "No such file or directory"; then
    UNGUARDED_CALLS_DETECTED=true
    echo "$OUTPUT" | while IFS= read -r line; do
        if echo "$line" | grep -q "No such file or directory"; then
            # Extract the command name from the error message like:
            # "/tmp/test_unguarded.sh: line 6: ls: No such file or directory"
            cmd=$(echo "$line" | awk -F': ' '{print $3}')
            echo "UNGUARDED CALL DETECTED: '$cmd' called without proper guarding"
        else
            echo "$line"
        fi
    done
else
    echo "$OUTPUT"
fi

echo
if [[ "$UNGUARDED_CALLS_DETECTED" == true ]]; then
    echo "❌ SECURITY ISSUE: Unguarded external command calls detected!"
    echo "   The library should use 'guard' function for all external commands."
    exit 1
else
    echo "✅ No unguarded external command calls detected."
    echo "   The library appears to properly guard its external command usage."
    exit 0
fi